### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by yellowfish621** [ayasa520/TaskScheduler#2]
Exception ignored in: <function TaskScheduler.__del__ at 0x7f7ae37549d0>
Traceback (most recent call last):
  File "/home/www/chatgpt-on-wechat-master/plugins/TaskScheduler/task_scheduler.py", line 92, in __del__
    self.scheduler.shutdown()
AttributeError: 'TaskScheduler' object has no attribute 'scheduler'

**Comment by ayasa520** [comment]
请给我更加详细的上下文。这个报错是什么情况下触发？插件功能是否正常？

**Comment by yellowfish621** [comment]
插件安装成功
启用时报错
![image](https://github.com/user-attachments/assets/8b63720e-836a-4cd4-99e1-775582d4d3f4)
找到错误日志显示的就是上面这段报错

**Comment by ayasa520** [comment]
发完整日志出来。此报错不是插件开启失败的原因，而是插件开启失败的结果。

**Comment by yellowfish621** [comment]
> 发完整日志出来。此报错不是插件开启失败的原因，而是插件开启失败的结果。
 | 插件开启失败), receiver=@8e405417742188d45f9827c5dab6a8624b95d17a9d28c4644a05c530083429b6
9|app  | Traceback (most recent call last):
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 598, in urlopen
9|app  |     httplib_response = self._make_request(conn, method, url,
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
9|app  |     six.raise_from(e, None)
9|app  |   File "<string>", line 2, in raise_from
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 383, in _make_request
9|app  |     httplib_response = conn.getresponse()
9|app  |   File "/usr/local/python3.8/lib/python3.8/http/client.py", line 1347, in getresponse
9|app  |     response.begin()
9|app  |   File "/usr/local/python3.8/lib/python3.8/http/client.py", line 307, in begin
9|app  |     version, status, reason = self._read_status()
9|app  |   File "/usr/local/python3.8/lib/python3.8/http/client.py", line 276, in _read_status
9|app  |     raise RemoteDisconnected("Remote end closed connection without"
9|app  | http.client.RemoteDisconnected: Remote end closed connection without response
9|app  | During handling of the above exception, another exception occurred:
9|app  | Traceback (most recent call last):
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
9|app  |     resp = conn.urlopen(
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 638, in urlopen
9|app  |     retries = retries.increment(method, url, error=e, _pool=self,
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 357, in increment
9|app  |     raise six.reraise(type(error), error, _stacktrace)
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/urllib3/packages/six.py", line 685, in reraise
9|app  |     raise value.with_traceback(tb)
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 598, in urlopen
9|app  |     httplib_response = self._make_request(conn, method, url,
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
9|app  |     six.raise_from(e, None)
9|app  |   File "<string>", line 2, in raise_from
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 383, in _make_request
9|app  |     httplib_response = conn.getresponse()
9|app  |   File "/usr/local/python3.8/lib/python3.8/http/client.py", line 1347, in getresponse
9|app  |     response.begin()
9|app  |   File "/usr/local/python3.8/lib/python3.8/http/client.py", line 307, in begin
9|app  |     version, status, reason = self._read_status()
9|app  |   File "/usr/local/python3.8/lib/python3.8/http/client.py", line 276, in _read_status
9|app  |     raise RemoteDisconnected("Remote end closed connection without"
9|app  | urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
9|app  | During handling of the above exception, another exception occurred:
9|app  | Traceback (most recent call last):
9|app  |   File "/home/www/chatgpt-on-wechat-master/lib/itchat/components/login.py", line 301, in maintain_loop
9|app  |     msgList, contactList = self.get_msg()
9|app  |   File "/home/www/chatgpt-on-wechat-master/lib/itchat/components/login.py", line 390, in get_msg
9|app  |     r = self.s.post(url, data=json.dumps(data),
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/requests/sessions.py", line 637, in post
9|app  |     return self.request("POST", url, data=data, json=json, **kwargs)
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
9|app  |     resp = self.send(prep, **send_kwargs)
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
9|app  |     r = adapter.send(request, **kwargs)
9|app  |   File "/usr/local/python3.8/lib/python3.8/site-packages/requests/adapters.py", line 682, in send
9|app  |     raise ConnectionError(err, request=request)
9|app  | requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by ayasa520** [comment]
@yellowfish621 我没有看出这些日志和插件开启失败有什么直接关系。请使用 fresh install 再次尝试并确保配置文件 config.json 存在

另外**完整**意味着你应该将 app.py 启动到最终报错之间的全部日志发出来
